package com.adobe.aem.guides.wknd.core.domains.product;

public abstract class ProductConstants {
    public static final String PRODUCT_PAGE_RESOURCE_TYPE = "wknd/components/productpage";

    //  product field names
    public static final String FIELD_NAME_ID                = "id";
    public static final String FIELD_NAME_TITLE             = "title";
    public static final String FIELD_NAME_DESCRIPTION       = "description";
    public static final String FIELD_NAME_IMAGE             = "image";
    public static final String FIELD_NAME_AUTOGENERATED     = "autogenerated";

}
